// Plain TypeScript types — not Zod schemas.
// Describes the enriched report returned from the API route to the client.

import type { GeminiFinding } from './geminiResponse';

export type Finding = GeminiFinding & {
  id: string;
  priority: number;
};

export type Summary = {
  total: number;
  high: number;
  medium: number;
  low: number;
};

export type AuditReport = {
  summary: Summary;
  findings: Finding[];
};

// Fixed application-owned limitations disclaimer — never generated by AI
export const LIMITATIONS_NOTE =
  'This is an AI-assisted review of a static screenshot. ' +
  'It is not a certified accessibility or usability audit. ' +
  'Findings should be verified and prioritized by a human designer or developer.';
